server setting

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -8,7 +8,8 @@ RUN go mod tidy
 
 COPY . .
 
-# ✅ 빌드 성공했는지 확인용 로그 추가
-RUN go build -o server . && echo "✅ Go build success" || echo "❌ Go build failed"
+# 디버깅용 로그 추가
+RUN echo "📦 빌드 중..." && ls -l /app && go build -o server . && echo "✅ build ok" || echo "❌ build failed"
+
 
 CMD ["./server"]
